apiVersion: shn.com/v1alpha1
kind: BookStore
metadata:
  name: bookstore-sample
spec:
  deploymentName: bookstore
  replicas: 3
  containerPort: 3000
  deploymentImageName: shn27/book-store
  deploymentImageTag: "4.0"